version: '3'
networks:
  app-tier:
    driver: bridge
services:
  fastapiapp:
    container_name: docker-fastapi
    # Build the Dockerfile that is in the api directory
    build: ./api
    ports:
      - "8000:8000"
    environment: 
      - MONGODB_CONNSTRING=mongodb://admin:password@mongodb
    # Mount the api directory within the container at /home/fastapi/app/api
    volumes:
      - ./api:/home/fastapi/app/api
      # This blank directory exists so that the local virtual environment doesn't get
      # used by the container. https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder#comment81906046_47153236
      - ./api/blank:/home/fastapi/app/api/env

    entrypoint: ["sh", "/home/fastapi/app/api/start.sh"]
    depends_on:
      - mongodb
    networks:
      - app-tier
  mongodb:
    container_name: docker-fastapi-mongodb
    # Using this image because of https://github.com/docker-library/mongo/issues/329#issuecomment-852129727
    image: bitnami/mongodb:latest
    environment:
      MONGODB_DATABASE: mydatabase
      MONGODB_ROOT_PASSWORD: password
      MONGODB_ROOT_USER: admin
      TEST_MONGO_URI: mongodb://admin:password@mongodb
    networks:
      - app-tier
    # To persist the data outside the container
    volumes:
      - mongodb_data_container:/data/db

  

volumes:
  mongodb_data_container: {}